name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

jobs:
  run:
    uses: borch-ai/.github/.github/workflows/go-ci-standalone.yml@d681ba06277e712137904d2254f98a138e50e4fe
    with:
      coverage-threshold: 91
    secrets: inherit
